[package]
name = "engine"
version = "0.1.1"
edition = "2021"

[dependencies]
bytemuck = "1.14.3"
gl = "0.14.0"
glfw = "0.55.0"
image = "0.25"
nalgebra-glm = "0.18.0"
egui_gl_glfw = "0.1.1"
egui = "0.26.2"
